library(dplyr)
library(plotly)
library(stringr)
library(rgdal)
library(tidyverse)
library(ggmap)
library(DT)
library(knitr)
library(leaflet)
library(tigris)
library(geojsonio)
library(leaflet)
library(maps)
library(sp)
library(shiny)
library(cssTools)
library(rsconnect)

source("API-Key.R")
register_google(key = key)
source("ui.R")
source("build-histogram.R")


rents_df <- read.csv("State_MedianRentalPrice_2Bedroom.csv", 
                     stringsAsFactors = FALSE)
states <- states(cb=T)

rents_df <- rename_if(rents_df, is.numeric, 
                      funs(str_replace(., "X2010.", "2010/")))
rents_df <- rename_if(rents_df, is.numeric, 
                      funs(str_replace(., "X2011.", "2011/")))
rents_df <- rename_if(rents_df, is.numeric, 
                      funs(str_replace(., "X2012.", "2012/")))
rents_df <- rename_if(rents_df, is.numeric, 
                      funs(str_replace(., "X2013.", "2013/")))
rents_df <- rename_if(rents_df, is.numeric, 
                      funs(str_replace(., "X2014.", "2014/")))
rents_df <- rename_if(rents_df, is.numeric, 
                      funs(str_replace(., "X2015.", "2015/")))
rents_df <- rename_if(rents_df, is.numeric, 
                      funs(str_replace(., "X2016.", "2016/")))
rents_df <- rename_if(rents_df, is.numeric, 
                      funs(str_replace(., "X2017.", "2017/")))
rents_df <- rename_if(rents_df, is.numeric, 
                      funs(str_replace(., "X2018.", "2018/")))
rents_df <- rename_if(rents_df, is.numeric, 
                      funs(str_replace(., "X2019.", "2019/")))

geo <- geocode(location = rents_df$RegionName, output = "latlon", 
               source = "google")
rents_df$lon <- geo$lon
rents_df$lat <- geo$lat
rents_df <- rents_df %>% rename(NAME = RegionName)

# geocode ________

state_rents <- merge(states, rents_df, by = "NAME")

bins <- c(500, 800, 1100, 1400, 1700, 2000, 2300, 
          2600, 2900, Inf)
pal <- colorBin("Reds", domain = state_rents$`2019/01`, bins = bins) 

labels <- sprintf(
  "<strong>%s</strong><br/>
  Rent Price: $%g ",
  state_rents$NAME, state_rents$`2019/01`
) %>% lapply(htmltools::HTML)

rents_map <- leaflet(state_rents) %>% 
  setView(-96, 37.8, 2) %>% 
  addTiles() %>% 
  addPolygons(
    fillColor = ~pal(state_rents$`2019/01`),
    weight = 2,
    opacity = 1,
    color = "white",
    dashArray = 2,
    fillOpacity = 6,
    highlight = highlightOptions(
      weight = 5,
      color = "#666",
      dashArray = "",
      fillOpacity = 6,
      bringToFront = TRUE),
    label = labels,
    labelOptions = labelOptions(
      style = list("font-weight" = "normal", padding = "3px 8px"),
      textsize = "15px", direction = "auto")) %>% 
  addLegend(pal = pal, values = ~state_rents$`2019/01`, opacity = 6, 
            title = NULL, position = "bottomright")


#Shiny Integration

server_final <- shinyServer(function(input, output) {
  
  output$rents_map <- renderLeaflet({
    
    bins <- c(500, 800, 1100, 1400, 1700, 2000, 2300, 
              2600, 2900, Inf)
    pal <- colorBin("Reds", domain = state_rents[[input$year_var]], bins = bins) 
    
    rents_map <- leaflet(state_rents) %>% 
      setView(-96, 37.8, 2) %>% 
      addTiles() %>% 
      addPolygons(
        fillColor = ~pal(state_rents[[input$year_var]]),
        weight = 2,
        opacity = 1,
        color = "white",
        dashArray = 2,
        fillOpacity = 6,
        highlight = highlightOptions(
          weight = 5,
          color = "#666",
          dashArray = "",
          fillOpacity = 6,
          bringToFront = TRUE),
        label = labels,
        labelOptions = labelOptions(
          style = list("font-weight" = "normal", padding = "3px 8px"),
          textsize = "15px", direction = "auto")) %>% 
      addLegend(rents_map, pal = pal, values = ~state_rents[[input$year_var]], 
                opacity = 6, title = NULL, position = "bottomright")
    
    
    labels <- sprintf(
      "<strong>%s</strong><br/>
      Average Rent Price: $%s ",
      state_rents$NAME, input$year_var
    ) %>% lapply(htmltools::HTML)
    
    rents_map
  })
  
  output$linechart <- renderPlot({
    chartData <- switch(input$city,
                        "Seattle" = list(Seattle_data$`2010/01`,
                                         Seattle_data$`2010/02`,
                                         Seattle_data$`2010/03`,
                                         Seattle_data$`2010/04`,
                                         Seattle_data$`2010/05`,
                                         Seattle_data$`2010/06`,
                                         Seattle_data$`2010/07`,
                                         Seattle_data$`2010/08`,
                                         Seattle_data$`2010/09`,
                                         Seattle_data$`2010/10`,
                                         Seattle_data$`2010/11`,
                                         Seattle_data$`2010/12`,
                                         Seattle_data$`2011/01`,
                                         Seattle_data$`2011/02`,
                                         Seattle_data$`2011/03`,
                                         Seattle_data$`2011/04`,
                                         Seattle_data$`2011/05`,
                                         Seattle_data$`2011/06`,
                                         Seattle_data$`2011/07`,
                                         Seattle_data$`2011/08`,
                                         Seattle_data$`2011/09`,
                                         Seattle_data$`2011/10`,
                                         Seattle_data$`2011/11`,
                                         Seattle_data$`2011/12`,
                                         Seattle_data$`2012/01`,
                                         Seattle_data$`2012/02`,
                                         Seattle_data$`2012/03`,
                                         Seattle_data$`2012/04`,
                                         Seattle_data$`2012/05`,
                                         Seattle_data$`2012/06`,
                                         Seattle_data$`2012/07`,
                                         Seattle_data$`2012/08`,
                                         Seattle_data$`2012/09`,
                                         Seattle_data$`2012/10`,
                                         Seattle_data$`2012/11`,
                                         Seattle_data$`2012/12`,
                                         Seattle_data$`2013/01`,
                                         Seattle_data$`2013/02`,
                                         Seattle_data$`2013/03`,
                                         Seattle_data$`2013/04`,
                                         Seattle_data$`2013/05`,
                                         Seattle_data$`2013/06`,
                                         Seattle_data$`2013/07`,
                                         Seattle_data$`2013/08`,
                                         Seattle_data$`2013/09`,
                                         Seattle_data$`2013/10`,
                                         Seattle_data$`2013/11`,
                                         Seattle_data$`2013/12`,
                                         Seattle_data$`2014/01`,
                                         Seattle_data$`2014/02`,
                                         Seattle_data$`2014/03`,
                                         Seattle_data$`2014/04`,
                                         Seattle_data$`2014/05`,
                                         Seattle_data$`2014/06`,
                                         Seattle_data$`2014/07`,
                                         Seattle_data$`2014/08`,
                                         Seattle_data$`2014/09`,
                                         Seattle_data$`2014/10`,
                                         Seattle_data$`2014/11`,
                                         Seattle_data$`2014/12`,
                                         Seattle_data$`2015/01`,
                                         Seattle_data$`2015/02`,
                                         Seattle_data$`2015/03`,
                                         Seattle_data$`2015/04`,
                                         Seattle_data$`2015/05`,
                                         Seattle_data$`2015/06`,
                                         Seattle_data$`2015/07`,
                                         Seattle_data$`2015/08`,
                                         Seattle_data$`2015/09`,
                                         Seattle_data$`2015/10`,
                                         Seattle_data$`2015/11`,
                                         Seattle_data$`2015/12`,
                                         Seattle_data$`2016/01`,
                                         Seattle_data$`2016/02`,
                                         Seattle_data$`2016/03`,
                                         Seattle_data$`2016/04`,
                                         Seattle_data$`2016/05`,
                                         Seattle_data$`2016/06`,
                                         Seattle_data$`2016/07`,
                                         Seattle_data$`2016/08`,
                                         Seattle_data$`2016/09`,
                                         Seattle_data$`2016/10`,
                                         Seattle_data$`2016/11`,
                                         Seattle_data$`2016/12`,
                                         Seattle_data$`2017/01`,
                                         Seattle_data$`2017/02`,
                                         Seattle_data$`2017/03`,
                                         Seattle_data$`2017/04`,
                                         Seattle_data$`2017/05`,
                                         Seattle_data$`2017/06`,
                                         Seattle_data$`2017/07`,
                                         Seattle_data$`2017/08`,
                                         Seattle_data$`2017/09`,
                                         Seattle_data$`2017/10`,
                                         Seattle_data$`2017/11`,
                                         Seattle_data$`2017/12`,
                                         Seattle_data$`2018/01`,
                                         Seattle_data$`2018/02`,
                                         Seattle_data$`2018/03`,
                                         Seattle_data$`2018/04`,
                                         Seattle_data$`2018/05`,
                                         Seattle_data$`2018/06`,
                                         Seattle_data$`2018/07`,
                                         Seattle_data$`2018/08`,
                                         Seattle_data$`2018/09`,
                                         Seattle_data$`2018/10`,
                                         Seattle_data$`2018/11`,
                                         Seattle_data$`2018/12`,
                                         Seattle_data$`2019/01`),
                        
                        "Los Angeles" = list(LA_data$`2010/01`,
                                             LA_data$`2010/02`,
                                             LA_data$`2010/03`,
                                             LA_data$`2010/04`,
                                             LA_data$`2010/05`,
                                             LA_data$`2010/06`,
                                             LA_data$`2010/07`,
                                             LA_data$`2010/08`,
                                             LA_data$`2010/09`,
                                             LA_data$`2010/10`,
                                             LA_data$`2010/11`,
                                             LA_data$`2010/12`,
                                             LA_data$`2011/01`,
                                             LA_data$`2011/02`,
                                             LA_data$`2011/03`,
                                             LA_data$`2011/04`,
                                             LA_data$`2011/05`,
                                             LA_data$`2011/06`,
                                             LA_data$`2011/07`,
                                             LA_data$`2011/08`,
                                             LA_data$`2011/09`,
                                             LA_data$`2011/10`,
                                             LA_data$`2011/11`,
                                             LA_data$`2011/12`,
                                             LA_data$`2012/01`,
                                             LA_data$`2012/02`,
                                             LA_data$`2012/03`,
                                             LA_data$`2012/04`,
                                             LA_data$`2012/05`,
                                             LA_data$`2012/06`,
                                             LA_data$`2012/07`,
                                             LA_data$`2012/08`,
                                             LA_data$`2012/09`,
                                             LA_data$`2012/10`,
                                             LA_data$`2012/11`,
                                             LA_data$`2012/12`,
                                             LA_data$`2013/01`,
                                             LA_data$`2013/02`,
                                             LA_data$`2013/03`,
                                             LA_data$`2013/04`,
                                             LA_data$`2013/05`,
                                             LA_data$`2013/06`,
                                             LA_data$`2013/07`,
                                             LA_data$`2013/08`,
                                             LA_data$`2013/09`,
                                             LA_data$`2013/10`,
                                             LA_data$`2013/11`,
                                             LA_data$`2013/12`,
                                             LA_data$`2014/01`,
                                             LA_data$`2014/02`,
                                             LA_data$`2014/03`,
                                             LA_data$`2014/04`,
                                             LA_data$`2014/05`,
                                             LA_data$`2014/06`,
                                             LA_data$`2014/07`,
                                             LA_data$`2014/08`,
                                             LA_data$`2014/09`,
                                             LA_data$`2014/10`,
                                             LA_data$`2014/11`,
                                             LA_data$`2014/12`,
                                             LA_data$`2015/01`,
                                             LA_data$`2015/02`,
                                             LA_data$`2015/03`,
                                             LA_data$`2015/04`,
                                             LA_data$`2015/05`,
                                             LA_data$`2015/06`,
                                             LA_data$`2015/07`,
                                             LA_data$`2015/08`,
                                             LA_data$`2015/09`,
                                             LA_data$`2015/10`,
                                             LA_data$`2015/11`,
                                             LA_data$`2015/12`,
                                             LA_data$`2016/01`,
                                             LA_data$`2016/02`,
                                             LA_data$`2016/03`,
                                             LA_data$`2016/04`,
                                             LA_data$`2016/05`,
                                             LA_data$`2016/06`,
                                             LA_data$`2016/07`,
                                             LA_data$`2016/08`,
                                             LA_data$`2016/09`,
                                             LA_data$`2016/10`,
                                             LA_data$`2016/11`,
                                             LA_data$`2016/12`,
                                             LA_data$`2017/01`,
                                             LA_data$`2017/02`,
                                             LA_data$`2017/03`,
                                             LA_data$`2017/04`,
                                             LA_data$`2017/05`,
                                             LA_data$`2017/06`,
                                             LA_data$`2017/07`,
                                             LA_data$`2017/08`,
                                             LA_data$`2017/09`,
                                             LA_data$`2017/10`,
                                             LA_data$`2017/11`,
                                             LA_data$`2017/12`,
                                             LA_data$`2018/01`,
                                             LA_data$`2018/02`,
                                             LA_data$`2018/03`,
                                             LA_data$`2018/04`,
                                             LA_data$`2018/05`,
                                             LA_data$`2018/06`,
                                             LA_data$`2018/07`,
                                             LA_data$`2018/08`,
                                             LA_data$`2018/09`,
                                             LA_data$`2018/10`,
                                             LA_data$`2018/11`,
                                             LA_data$`2018/12`,
                                             LA_data$`2019/01`),
                        
                        "New York" = list(NY_data$`2010/01`,
                                          NY_data$`2010/02`,
                                          NY_data$`2010/03`,
                                          NY_data$`2010/04`,
                                          NY_data$`2010/05`,
                                          NY_data$`2010/06`,
                                          NY_data$`2010/07`,
                                          NY_data$`2010/08`,
                                          NY_data$`2010/09`,
                                          NY_data$`2010/10`,
                                          NY_data$`2010/11`,
                                          NY_data$`2010/12`,
                                          NY_data$`2011/01`,
                                          NY_data$`2011/02`,
                                          NY_data$`2011/03`,
                                          NY_data$`2011/04`,
                                          NY_data$`2011/05`,
                                          NY_data$`2011/06`,
                                          NY_data$`2011/07`,
                                          NY_data$`2011/08`,
                                          NY_data$`2011/09`,
                                          NY_data$`2011/10`,
                                          NY_data$`2011/11`,
                                          NY_data$`2011/12`,
                                          NY_data$`2012/01`,
                                          NY_data$`2012/02`,
                                          NY_data$`2012/03`,
                                          NY_data$`2012/04`,
                                          NY_data$`2012/05`,
                                          NY_data$`2012/06`,
                                          NY_data$`2012/07`,
                                          NY_data$`2012/08`,
                                          NY_data$`2012/09`,
                                          NY_data$`2012/10`,
                                          NY_data$`2012/11`,
                                          NY_data$`2012/12`,
                                          NY_data$`2013/01`,
                                          NY_data$`2013/02`,
                                          NY_data$`2013/03`,
                                          NY_data$`2013/04`,
                                          NY_data$`2013/05`,
                                          NY_data$`2013/06`,
                                          NY_data$`2013/07`,
                                          NY_data$`2013/08`,
                                          NY_data$`2013/09`,
                                          NY_data$`2013/10`,
                                          NY_data$`2013/11`,
                                          NY_data$`2013/12`,
                                          NY_data$`2014/01`,
                                          NY_data$`2014/02`,
                                          NY_data$`2014/03`,
                                          NY_data$`2014/04`,
                                          NY_data$`2014/05`,
                                          NY_data$`2014/06`,
                                          NY_data$`2014/07`,
                                          NY_data$`2014/08`,
                                          NY_data$`2014/09`,
                                          NY_data$`2014/10`,
                                          NY_data$`2014/11`,
                                          NY_data$`2014/12`,
                                          NY_data$`2015/01`,
                                          NY_data$`2015/02`,
                                          NY_data$`2015/03`,
                                          NY_data$`2015/04`,
                                          NY_data$`2015/05`,
                                          NY_data$`2015/06`,
                                          NY_data$`2015/07`,
                                          NY_data$`2015/08`,
                                          NY_data$`2015/09`,
                                          NY_data$`2015/10`,
                                          NY_data$`2015/11`,
                                          NY_data$`2015/12`,
                                          NY_data$`2016/01`,
                                          NY_data$`2016/02`,
                                          NY_data$`2016/03`,
                                          NY_data$`2016/04`,
                                          NY_data$`2016/05`,
                                          NY_data$`2016/06`,
                                          NY_data$`2016/07`,
                                          NY_data$`2016/08`,
                                          NY_data$`2016/09`,
                                          NY_data$`2016/10`,
                                          NY_data$`2016/11`,
                                          NY_data$`2016/12`,
                                          NY_data$`2017/01`,
                                          NY_data$`2017/02`,
                                          NY_data$`2017/03`,
                                          NY_data$`2017/04`,
                                          NY_data$`2017/05`,
                                          NY_data$`2017/06`,
                                          NY_data$`2017/07`,
                                          NY_data$`2017/08`,
                                          NY_data$`2017/09`,
                                          NY_data$`2017/10`,
                                          NY_data$`2017/11`,
                                          NY_data$`2017/12`,
                                          NY_data$`2018/01`,
                                          NY_data$`2018/02`,
                                          NY_data$`2018/03`,
                                          NY_data$`2018/04`,
                                          NY_data$`2018/05`,
                                          NY_data$`2018/06`,
                                          NY_data$`2018/07`,
                                          NY_data$`2018/08`,
                                          NY_data$`2018/09`,
                                          NY_data$`2018/10`,
                                          NY_data$`2018/11`,
                                          NY_data$`2018/12`,
                                          NY_data$`2019/01`),
                        
                        "San Francisco" = list(SF_data$`2010/01`,
                                               SF_data$`2010/02`,
                                               SF_data$`2010/03`,
                                               SF_data$`2010/04`,
                                               SF_data$`2010/05`,
                                               SF_data$`2010/06`,
                                               SF_data$`2010/07`,
                                               SF_data$`2010/08`,
                                               SF_data$`2010/09`,
                                               SF_data$`2010/10`,
                                               SF_data$`2010/11`,
                                               SF_data$`2010/12`,
                                               SF_data$`2011/01`,
                                               SF_data$`2011/02`,
                                               SF_data$`2011/03`,
                                               SF_data$`2011/04`,
                                               SF_data$`2011/05`,
                                               SF_data$`2011/06`,
                                               SF_data$`2011/07`,
                                               SF_data$`2011/08`,
                                               SF_data$`2011/09`,
                                               SF_data$`2011/10`,
                                               SF_data$`2011/11`,
                                               SF_data$`2011/12`,
                                               SF_data$`2012/01`,
                                               SF_data$`2012/02`,
                                               SF_data$`2012/03`,
                                               SF_data$`2012/04`,
                                               SF_data$`2012/05`,
                                               SF_data$`2012/06`,
                                               SF_data$`2012/07`,
                                               SF_data$`2012/08`,
                                               SF_data$`2012/09`,
                                               SF_data$`2012/10`,
                                               SF_data$`2012/11`,
                                               SF_data$`2012/12`,
                                               SF_data$`2013/01`,
                                               SF_data$`2013/02`,
                                               SF_data$`2013/03`,
                                               SF_data$`2013/04`,
                                               SF_data$`2013/05`,
                                               SF_data$`2013/06`,
                                               SF_data$`2013/07`,
                                               SF_data$`2013/08`,
                                               SF_data$`2013/09`,
                                               SF_data$`2013/10`,
                                               SF_data$`2013/11`,
                                               SF_data$`2013/12`,
                                               SF_data$`2014/01`,
                                               SF_data$`2014/02`,
                                               SF_data$`2014/03`,
                                               SF_data$`2014/04`,
                                               SF_data$`2014/05`,
                                               SF_data$`2014/06`,
                                               SF_data$`2014/07`,
                                               SF_data$`2014/08`,
                                               SF_data$`2014/09`,
                                               SF_data$`2014/10`,
                                               SF_data$`2014/11`,
                                               SF_data$`2014/12`,
                                               SF_data$`2015/01`,
                                               SF_data$`2015/02`,
                                               SF_data$`2015/03`,
                                               SF_data$`2015/04`,
                                               SF_data$`2015/05`,
                                               SF_data$`2015/06`,
                                               SF_data$`2015/07`,
                                               SF_data$`2015/08`,
                                               SF_data$`2015/09`,
                                               SF_data$`2015/10`,
                                               SF_data$`2015/11`,
                                               SF_data$`2015/12`,
                                               SF_data$`2016/01`,
                                               SF_data$`2016/02`,
                                               SF_data$`2016/03`,
                                               SF_data$`2016/04`,
                                               SF_data$`2016/05`,
                                               SF_data$`2016/06`,
                                               SF_data$`2016/07`,
                                               SF_data$`2016/08`,
                                               SF_data$`2016/09`,
                                               SF_data$`2016/10`,
                                               SF_data$`2016/11`,
                                               SF_data$`2016/12`,
                                               SF_data$`2017/01`,
                                               SF_data$`2017/02`,
                                               SF_data$`2017/03`,
                                               SF_data$`2017/04`,
                                               SF_data$`2017/05`,
                                               SF_data$`2017/06`,
                                               SF_data$`2017/07`,
                                               SF_data$`2017/08`,
                                               SF_data$`2017/09`,
                                               SF_data$`2017/10`,
                                               SF_data$`2017/11`,
                                               SF_data$`2017/12`,
                                               SF_data$`2018/01`,
                                               SF_data$`2018/02`,
                                               SF_data$`2018/03`,
                                               SF_data$`2018/04`,
                                               SF_data$`2018/05`,
                                               SF_data$`2018/06`,
                                               SF_data$`2018/07`,
                                               SF_data$`2018/08`,
                                               SF_data$`2018/09`,
                                               SF_data$`2018/10`,
                                               SF_data$`2018/11`,
                                               SF_data$`2018/12`,
                                               SF_data$`2019/01`),
                        
                        "United States" = list(US_data$`2010/01`,
                                               US_data$`2010/02`,
                                               US_data$`2010/03`,
                                               US_data$`2010/04`,
                                               US_data$`2010/05`,
                                               US_data$`2010/06`,
                                               US_data$`2010/07`,
                                               US_data$`2010/08`,
                                               US_data$`2010/09`,
                                               US_data$`2010/10`,
                                               US_data$`2010/11`,
                                               US_data$`2010/12`,
                                               US_data$`2011/01`,
                                               US_data$`2011/02`,
                                               US_data$`2011/03`,
                                               US_data$`2011/04`,
                                               US_data$`2011/05`,
                                               US_data$`2011/06`,
                                               US_data$`2011/07`,
                                               US_data$`2011/08`,
                                               US_data$`2011/09`,
                                               US_data$`2011/10`,
                                               US_data$`2011/11`,
                                               US_data$`2011/12`,
                                               US_data$`2012/01`,
                                               US_data$`2012/02`,
                                               US_data$`2012/03`,
                                               US_data$`2012/04`,
                                               US_data$`2012/05`,
                                               US_data$`2012/06`,
                                               US_data$`2012/07`,
                                               US_data$`2012/08`,
                                               US_data$`2012/09`,
                                               US_data$`2012/10`,
                                               US_data$`2012/11`,
                                               US_data$`2012/12`,
                                               US_data$`2013/01`,
                                               US_data$`2013/02`,
                                               US_data$`2013/03`,
                                               US_data$`2013/04`,
                                               US_data$`2013/05`,
                                               US_data$`2013/06`,
                                               US_data$`2013/07`,
                                               US_data$`2013/08`,
                                               US_data$`2013/09`,
                                               US_data$`2013/10`,
                                               US_data$`2013/11`,
                                               US_data$`2013/12`,
                                               US_data$`2014/01`,
                                               US_data$`2014/02`,
                                               US_data$`2014/03`,
                                               US_data$`2014/04`,
                                               US_data$`2014/05`,
                                               US_data$`2014/06`,
                                               US_data$`2014/07`,
                                               US_data$`2014/08`,
                                               US_data$`2014/09`,
                                               US_data$`2014/10`,
                                               US_data$`2014/11`,
                                               US_data$`2014/12`,
                                               US_data$`2015/01`,
                                               US_data$`2015/02`,
                                               US_data$`2015/03`,
                                               US_data$`2015/04`,
                                               US_data$`2015/05`,
                                               US_data$`2015/06`,
                                               US_data$`2015/07`,
                                               US_data$`2015/08`,
                                               US_data$`2015/09`,
                                               US_data$`2015/10`,
                                               US_data$`2015/11`,
                                               US_data$`2015/12`,
                                               US_data$`2016/01`,
                                               US_data$`2016/02`,
                                               US_data$`2016/03`,
                                               US_data$`2016/04`,
                                               US_data$`2016/05`,
                                               US_data$`2016/06`,
                                               US_data$`2016/07`,
                                               US_data$`2016/08`,
                                               US_data$`2016/09`,
                                               US_data$`2016/10`,
                                               US_data$`2016/11`,
                                               US_data$`2016/12`,
                                               US_data$`2017/01`,
                                               US_data$`2017/02`,
                                               US_data$`2017/03`,
                                               US_data$`2017/04`,
                                               US_data$`2017/05`,
                                               US_data$`2017/06`,
                                               US_data$`2017/07`,
                                               US_data$`2017/08`,
                                               US_data$`2017/09`,
                                               US_data$`2017/10`,
                                               US_data$`2017/11`,
                                               US_data$`2017/12`,
                                               US_data$`2018/01`,
                                               US_data$`2018/02`,
                                               US_data$`2018/03`,
                                               US_data$`2018/04`,
                                               US_data$`2018/05`,
                                               US_data$`2018/06`,
                                               US_data$`2018/07`,
                                               US_data$`2018/08`,
                                               US_data$`2018/09`,
                                               US_data$`2018/10`,
                                               US_data$`2018/11`,
                                               US_data$`2018/12`,
                                               US_data$`2019/01`),
                        
                        "Chicago" = list(Chicago_data$`2010/01`,
                                         Chicago_data$`2010/02`,
                                         Chicago_data$`2010/03`,
                                         Chicago_data$`2010/04`,
                                         Chicago_data$`2010/05`,
                                         Chicago_data$`2010/06`,
                                         Chicago_data$`2010/07`,
                                         Chicago_data$`2010/08`,
                                         Chicago_data$`2010/09`,
                                         Chicago_data$`2010/10`,
                                         Chicago_data$`2010/11`,
                                         Chicago_data$`2010/12`,
                                         Chicago_data$`2011/01`,
                                         Chicago_data$`2011/02`,
                                         Chicago_data$`2011/03`,
                                         Chicago_data$`2011/04`,
                                         Chicago_data$`2011/05`,
                                         Chicago_data$`2011/06`,
                                         Chicago_data$`2011/07`,
                                         Chicago_data$`2011/08`,
                                         Chicago_data$`2011/09`,
                                         Chicago_data$`2011/10`,
                                         Chicago_data$`2011/11`,
                                         Chicago_data$`2011/12`,
                                         Chicago_data$`2012/01`,
                                         Chicago_data$`2012/02`,
                                         Chicago_data$`2012/03`,
                                         Chicago_data$`2012/04`,
                                         Chicago_data$`2012/05`,
                                         Chicago_data$`2012/06`,
                                         Chicago_data$`2012/07`,
                                         Chicago_data$`2012/08`,
                                         Chicago_data$`2012/09`,
                                         Chicago_data$`2012/10`,
                                         Chicago_data$`2012/11`,
                                         Chicago_data$`2012/12`,
                                         Chicago_data$`2013/01`,
                                         Chicago_data$`2013/02`,
                                         Chicago_data$`2013/03`,
                                         Chicago_data$`2013/04`,
                                         Chicago_data$`2013/05`,
                                         Chicago_data$`2013/06`,
                                         Chicago_data$`2013/07`,
                                         Chicago_data$`2013/08`,
                                         Chicago_data$`2013/09`,
                                         Chicago_data$`2013/10`,
                                         Chicago_data$`2013/11`,
                                         Chicago_data$`2013/12`,
                                         Chicago_data$`2014/01`,
                                         Chicago_data$`2014/02`,
                                         Chicago_data$`2014/03`,
                                         Chicago_data$`2014/04`,
                                         Chicago_data$`2014/05`,
                                         Chicago_data$`2014/06`,
                                         Chicago_data$`2014/07`,
                                         Chicago_data$`2014/08`,
                                         Chicago_data$`2014/09`,
                                         Chicago_data$`2014/10`,
                                         Chicago_data$`2014/11`,
                                         Chicago_data$`2014/12`,
                                         Chicago_data$`2015/01`,
                                         Chicago_data$`2015/02`,
                                         Chicago_data$`2015/03`,
                                         Chicago_data$`2015/04`,
                                         Chicago_data$`2015/05`,
                                         Chicago_data$`2015/06`,
                                         Chicago_data$`2015/07`,
                                         Chicago_data$`2015/08`,
                                         Chicago_data$`2015/09`,
                                         Chicago_data$`2015/10`,
                                         Chicago_data$`2015/11`,
                                         Chicago_data$`2015/12`,
                                         Chicago_data$`2016/01`,
                                         Chicago_data$`2016/02`,
                                         Chicago_data$`2016/03`,
                                         Chicago_data$`2016/04`,
                                         Chicago_data$`2016/05`,
                                         Chicago_data$`2016/06`,
                                         Chicago_data$`2016/07`,
                                         Chicago_data$`2016/08`,
                                         Chicago_data$`2016/09`,
                                         Chicago_data$`2016/10`,
                                         Chicago_data$`2016/11`,
                                         Chicago_data$`2016/12`,
                                         Chicago_data$`2017/01`,
                                         Chicago_data$`2017/02`,
                                         Chicago_data$`2017/03`,
                                         Chicago_data$`2017/04`,
                                         Chicago_data$`2017/05`,
                                         Chicago_data$`2017/06`,
                                         Chicago_data$`2017/07`,
                                         Chicago_data$`2017/08`,
                                         Chicago_data$`2017/09`,
                                         Chicago_data$`2017/10`,
                                         Chicago_data$`2017/11`,
                                         Chicago_data$`2017/12`,
                                         Chicago_data$`2018/01`,
                                         Chicago_data$`2018/02`,
                                         Chicago_data$`2018/03`,
                                         Chicago_data$`2018/04`,
                                         Chicago_data$`2018/05`,
                                         Chicago_data$`2018/06`,
                                         Chicago_data$`2018/07`,
                                         Chicago_data$`2018/08`,
                                         Chicago_data$`2018/09`,
                                         Chicago_data$`2018/10`,
                                         Chicago_data$`2018/11`,
                                         Chicago_data$`2018/12`,
                                         Chicago_data$`2019/01`)
                        
    )
    
    chartTitle <- switch(input$city,
                         
                         "Seattle, WA" = "Seattle",
                         "Los Angeles-Long Beach-Anaheim, CA" = "Los Angeles",
                         "New York, NY" = "New York",
                         "Chicago, IL" = "Chicago",
                         "San Francisco, CA" = "San Francisco",
                         "United States" = "United States"
                         
    )
    
    Pure_city_data_points <- select(City_data, -RegionName, -SizeRank)
    Xvalues <- filter(City_data, SizeRank == "size") %>% select(-RegionName, -SizeRank)
    
    yrange <- c(0,3500)
    xrange <- range(num_year)
    plot(xrange,yrange,type="n",xlab="",ylab="Rental Prices (in Dollars)",cex.lab=1.5,
         main=paste("Changes in Rental Prices in ", chartTitle))
    lines(Xvalues,chartData,col="firebrick3",lwd=3)
    legend(2010,3450,c("Rental Price Trends"), 
           col="firebrick3", pch=15,ncol=300,bty ="n",cex=1.1)
    
  }, height = 600, width = 700)
  
 #closes candances output
  
  output$scatter <- renderPlotly({
    rents_year <- rents_year %>%
      filter(rents_year[[input$area]] > input$price_range[1],
             rents_year[[input$area]] < input$price_range[2])
    scatter_plot <- plot_ly(rents_year) %>%
      add_trace(x = rents_year$SizeRank,
                y = rents_year[[input$area]],
                type = "scatter",
                mode = "markers",
                hoverinfo = "text",
                color = rents_year[[input$area]],
                colors = c("blue", "red"),
                text = ~paste0(RegionName, "<br>",
                               "Average Rental Price: $",
                               round(rents_year[[input$area]], digits = 2),
                               "<br>",
                               "Size Rank: ", rents_year$SizeRank)) %>%
      layout(title = "Price vs Area",
             xaxis = list(title = "Size Rank"),
             yaxis = list(title = "Rental Price ($)",
                          showlegend = FALSE))
    if (input$box) {
      scatter_plot <-
        add_lines(scatter_plot, x = rents_year$SizeRank, y = ~fitted(
          loess(rents_year[[input$area]] ~ rents_year$SizeRank)),
          line = list(color = "black"),
          name = "Trendline",
          showlegend = FALSE)
    }
    colorbar(scatter_plot,
             title = "Rental Price ($)")
    scatter_plot
  })
  output$histogram <- renderPlot({
    return(histogram(three, input$city1, input$city2))
  })
})

